-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity DMA24bUnit_mm2s_DMA24b_mm2s_fetch is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    mm_fifo1_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    mm_fifo1_full_n : IN STD_LOGIC;
    mm_fifo1_write : OUT STD_LOGIC;
    mm_buffer : IN STD_LOGIC_VECTOR (63 downto 0);
    img_w : IN STD_LOGIC_VECTOR (11 downto 0);
    img_h : IN STD_LOGIC_VECTOR (11 downto 0);
    img_w_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    img_w_out_full_n : IN STD_LOGIC;
    img_w_out_write : OUT STD_LOGIC;
    img_h_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    img_h_out_full_n : IN STD_LOGIC;
    img_h_out_write : OUT STD_LOGIC );
end;


architecture behav of DMA24bUnit_mm2s_DMA24b_mm2s_fetch is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (16 downto 0) := "00000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (16 downto 0) := "00000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (16 downto 0) := "00000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (16 downto 0) := "00000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (16 downto 0) := "00000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (16 downto 0) := "00000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (16 downto 0) := "00001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (16 downto 0) := "00010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (16 downto 0) := "00100000000000000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (16 downto 0) := "01000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv11_27 : STD_LOGIC_VECTOR (10 downto 0) := "00000100111";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv24_CCD : STD_LOGIC_VECTOR (23 downto 0) := "000000000000110011001101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal gmem_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal gmem_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln15_reg_508 : STD_LOGIC_VECTOR (0 downto 0);
    signal mm_fifo1_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln15_reg_508_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal img_w_out_blk_n : STD_LOGIC;
    signal img_h_out_blk_n : STD_LOGIC;
    signal indvar_flatten_reg_191 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_reg_438 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp22_i_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp22_i_reg_444 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln13_fu_252_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln13_reg_448 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_2_cast_reg_453 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln13_1_fu_285_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln13_1_reg_459 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal sext_ln14_fu_322_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln14_reg_469 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln10_fu_334_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln10_reg_474 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln14_fu_340_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln14_reg_479 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal empty_fu_375_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal empty_reg_487 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln14_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1_reg_492 : STD_LOGIC_VECTOR (59 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal add_ln15_1_fu_409_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_state16_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln15_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_mm_buffer_V_reg_512 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state16 : STD_LOGIC;
    signal j_reg_180 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal sext_ln15_1_fu_399_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln_fu_202_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_fu_216_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln12_1_fu_224_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln12_fu_212_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal beats_per_line_fu_228_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_420_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal sub_ln13_fu_264_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_1_cast_fu_269_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln13_fu_279_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln13_1_fu_291_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln15_1_fu_304_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln1_fu_296_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln15_fu_312_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln15_fu_316_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln10_fu_326_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln10_1_fu_330_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_shl3_i_fu_351_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal p_shl4_i_fu_363_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl3_cast11_i_fu_359_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_shl4_cast12_i_fu_371_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_cast_i_fu_381_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_62_fu_384_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_420_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_420_ce : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component DMA24bUnit_mm2s_mul_mul_11s_13ns_24_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    mul_mul_11s_13ns_24_4_1_U1 : component DMA24bUnit_mm2s_mul_mul_11s_13ns_24_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 11,
        din1_WIDTH => 13,
        dout_WIDTH => 24)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => beats_per_line_fu_228_p2,
        din1 => grp_fu_420_p1,
        ce => grp_fu_420_ce,
        dout => grp_fu_420_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln14_fu_346_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state16) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state16)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state16);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_reg_191_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_fu_415_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_191 <= add_ln15_1_fu_409_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                indvar_flatten_reg_191 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;

    j_reg_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                j_reg_180 <= ap_const_lv12_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                j_reg_180 <= add_ln14_reg_479;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                    add_ln10_reg_474(11 downto 3) <= add_ln10_fu_334_p2(11 downto 3);
                    sext_ln14_reg_469(31 downto 3) <= sext_ln14_fu_322_p1(31 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln14_reg_479 <= add_ln14_fu_340_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                cmp22_i_reg_444 <= cmp22_i_fu_246_p2;
                tmp_reg_438 <= beats_per_line_fu_228_p2(10 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln15_reg_508 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_mm_buffer_V_reg_512 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln14_fu_346_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    empty_reg_487(23 downto 7) <= empty_fu_375_p2(23 downto 7);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln15_reg_508 <= icmp_ln15_fu_415_p2;
                icmp_ln15_reg_508_pp0_iter1_reg <= icmp_ln15_reg_508;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_reg_438 = ap_const_lv1_1))) then
                sub_ln13_1_reg_459 <= sub_ln13_1_fu_285_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                tmp_2_cast_reg_453 <= grp_fu_420_p2(22 downto 17);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (tmp_reg_438 = ap_const_lv1_1))) then
                trunc_ln13_reg_448 <= trunc_ln13_fu_252_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (cmp22_i_reg_444 = ap_const_lv1_1))) then
                trunc_ln1_reg_492 <= empty_62_fu_384_p2(63 downto 4);
            end if;
        end if;
    end process;
    sext_ln14_reg_469(2 downto 0) <= "000";
    add_ln10_reg_474(2 downto 0) <= "000";
    empty_reg_487(6 downto 0) <= "0000000";

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, m_axi_gmem_ARREADY, img_w_out_full_n, img_h_out_full_n, ap_CS_fsm_state9, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, cmp22_i_reg_444, ap_CS_fsm_state7, icmp_ln14_fu_346_p2, ap_CS_fsm_state8, ap_enable_reg_pp0_iter0, icmp_ln15_fu_415_p2, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or (img_h_out_full_n = ap_const_logic_0) or (img_w_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((icmp_ln14_fu_346_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (cmp22_i_reg_444 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                if (((m_axi_gmem_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln15_fu_415_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and not(((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((icmp_ln15_fu_415_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln10_fu_334_p2 <= std_logic_vector(unsigned(zext_ln10_fu_326_p1) + unsigned(zext_ln10_1_fu_330_p1));
    add_ln14_fu_340_p2 <= std_logic_vector(unsigned(j_reg_180) + unsigned(ap_const_lv12_1));
    add_ln15_1_fu_409_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_191) + unsigned(ap_const_lv12_1));
    add_ln15_fu_316_p2 <= std_logic_vector(unsigned(shl_ln1_fu_296_p3) + unsigned(sext_ln15_fu_312_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(15);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state19 <= ap_CS_fsm(16);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(m_axi_gmem_RVALID, mm_fifo1_full_n, ap_enable_reg_pp0_iter1, icmp_ln15_reg_508, ap_enable_reg_pp0_iter2, icmp_ln15_reg_508_pp0_iter1_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((m_axi_gmem_RVALID = ap_const_logic_0) and (icmp_ln15_reg_508 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((icmp_ln15_reg_508_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (mm_fifo1_full_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(m_axi_gmem_RVALID, mm_fifo1_full_n, ap_enable_reg_pp0_iter1, icmp_ln15_reg_508, ap_enable_reg_pp0_iter2, icmp_ln15_reg_508_pp0_iter1_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_gmem_RVALID = ap_const_logic_0) and (icmp_ln15_reg_508 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((icmp_ln15_reg_508_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (mm_fifo1_full_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(m_axi_gmem_RVALID, mm_fifo1_full_n, ap_enable_reg_pp0_iter1, icmp_ln15_reg_508, ap_enable_reg_pp0_iter2, icmp_ln15_reg_508_pp0_iter1_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_gmem_RVALID = ap_const_logic_0) and (icmp_ln15_reg_508 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((icmp_ln15_reg_508_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (mm_fifo1_full_n = ap_const_logic_0)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, img_w_out_full_n, img_h_out_full_n)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or (img_h_out_full_n = ap_const_logic_0) or (img_w_out_full_n = ap_const_logic_0));
    end process;

        ap_block_state16_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state17_pp0_stage0_iter1_assign_proc : process(m_axi_gmem_RVALID, icmp_ln15_reg_508)
    begin
                ap_block_state17_pp0_stage0_iter1 <= ((m_axi_gmem_RVALID = ap_const_logic_0) and (icmp_ln15_reg_508 = ap_const_lv1_0));
    end process;


    ap_block_state18_pp0_stage0_iter2_assign_proc : process(mm_fifo1_full_n, icmp_ln15_reg_508_pp0_iter1_reg)
    begin
                ap_block_state18_pp0_stage0_iter2 <= ((icmp_ln15_reg_508_pp0_iter1_reg = ap_const_lv1_0) and (mm_fifo1_full_n = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state16_assign_proc : process(icmp_ln15_fu_415_p2)
    begin
        if ((icmp_ln15_fu_415_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state16 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state16 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state7, icmp_ln14_fu_346_p2)
    begin
        if (((icmp_ln14_fu_346_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    beats_per_line_fu_228_p2 <= std_logic_vector(unsigned(zext_ln12_1_fu_224_p1) - unsigned(zext_ln12_fu_212_p1));
    cmp22_i_fu_246_p2 <= "1" when (signed(beats_per_line_fu_228_p2) > signed(ap_const_lv11_27)) else "0";
    empty_62_fu_384_p2 <= std_logic_vector(signed(p_cast_i_fu_381_p1) + signed(mm_buffer));
    empty_fu_375_p2 <= std_logic_vector(unsigned(p_shl3_cast11_i_fu_359_p1) - unsigned(p_shl4_cast12_i_fu_371_p1));

    gmem_blk_n_AR_assign_proc : process(m_axi_gmem_ARREADY, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            gmem_blk_n_AR <= m_axi_gmem_ARREADY;
        else 
            gmem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(m_axi_gmem_RVALID, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln15_reg_508)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln15_reg_508 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            gmem_blk_n_R <= m_axi_gmem_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_420_ce_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_w_out_full_n, img_h_out_full_n, ap_CS_fsm_state4, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state4) or (not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or (img_h_out_full_n = ap_const_logic_0) or (img_w_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_fu_420_ce <= ap_const_logic_1;
        else 
            grp_fu_420_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_420_p1 <= ap_const_lv24_CCD(13 - 1 downto 0);
    icmp_ln14_fu_346_p2 <= "1" when (j_reg_180 = img_h) else "0";
    icmp_ln15_fu_415_p2 <= "1" when (indvar_flatten_reg_191 = add_ln10_reg_474) else "0";

    img_h_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_h_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_h_out_blk_n <= img_h_out_full_n;
        else 
            img_h_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_h_out_din <= img_h;

    img_h_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_w_out_full_n, img_h_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or (img_h_out_full_n = ap_const_logic_0) or (img_w_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_h_out_write <= ap_const_logic_1;
        else 
            img_h_out_write <= ap_const_logic_0;
        end if; 
    end process;


    img_w_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_w_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_w_out_blk_n <= img_w_out_full_n;
        else 
            img_w_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_w_out_din <= img_w;

    img_w_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_w_out_full_n, img_h_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or (img_h_out_full_n = ap_const_logic_0) or (img_w_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_w_out_write <= ap_const_logic_1;
        else 
            img_w_out_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state7, icmp_ln14_fu_346_p2)
    begin
        if (((icmp_ln14_fu_346_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_ARADDR <= sext_ln15_1_fu_399_p1;
    m_axi_gmem_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_ARID <= ap_const_lv1_0;
    m_axi_gmem_ARLEN <= sext_ln14_reg_469;
    m_axi_gmem_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_ARUSER <= ap_const_lv1_0;

    m_axi_gmem_ARVALID_assign_proc : process(m_axi_gmem_ARREADY, ap_CS_fsm_state9)
    begin
        if (((m_axi_gmem_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_gmem_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_AWID <= ap_const_lv1_0;
    m_axi_gmem_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_AWVALID <= ap_const_logic_0;
    m_axi_gmem_BREADY <= ap_const_logic_0;

    m_axi_gmem_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln15_reg_508, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln15_reg_508 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            m_axi_gmem_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_WDATA <= ap_const_lv128_lc_1;
    m_axi_gmem_WID <= ap_const_lv1_0;
    m_axi_gmem_WLAST <= ap_const_logic_0;
    m_axi_gmem_WSTRB <= ap_const_lv16_0;
    m_axi_gmem_WUSER <= ap_const_lv1_0;
    m_axi_gmem_WVALID <= ap_const_logic_0;

    mm_fifo1_blk_n_assign_proc : process(mm_fifo1_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln15_reg_508_pp0_iter1_reg)
    begin
        if (((icmp_ln15_reg_508_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            mm_fifo1_blk_n <= mm_fifo1_full_n;
        else 
            mm_fifo1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mm_fifo1_din <= data_mm_buffer_V_reg_512;

    mm_fifo1_write_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln15_reg_508_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln15_reg_508_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            mm_fifo1_write <= ap_const_logic_1;
        else 
            mm_fifo1_write <= ap_const_logic_0;
        end if; 
    end process;

        p_cast_i_fu_381_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_reg_487),64));

    p_shl3_cast11_i_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl3_i_fu_351_p3),24));
    p_shl3_i_fu_351_p3 <= (j_reg_180 & ap_const_lv11_0);
    p_shl4_cast12_i_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl4_i_fu_363_p3),24));
    p_shl4_i_fu_363_p3 <= (j_reg_180 & ap_const_lv7_0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln13_1_fu_291_p3 <= 
        sub_ln13_1_reg_459 when (tmp_reg_438(0) = '1') else 
        tmp_2_cast_reg_453;
    select_ln13_fu_279_p3 <= 
        tmp_1_cast_fu_269_p4 when (tmp_reg_438(0) = '1') else 
        tmp_2_cast_reg_453;
        sext_ln14_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln15_fu_316_p2),32));

        sext_ln15_1_fu_399_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_reg_492),64));

        sext_ln15_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln15_1_fu_304_p3),11));

    shl_ln15_1_fu_304_p3 <= (select_ln13_1_fu_291_p3 & ap_const_lv3_0);
    shl_ln1_fu_296_p3 <= (select_ln13_1_fu_291_p3 & ap_const_lv5_0);
    shl_ln_fu_216_p3 <= (trunc_ln_fu_202_p4 & ap_const_lv2_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln13_1_fu_285_p2 <= std_logic_vector(unsigned(ap_const_lv6_0) - unsigned(select_ln13_fu_279_p3));
    sub_ln13_fu_264_p2 <= std_logic_vector(unsigned(ap_const_lv23_0) - unsigned(trunc_ln13_reg_448));
    tmp_1_cast_fu_269_p4 <= sub_ln13_fu_264_p2(22 downto 17);
    trunc_ln13_fu_252_p1 <= grp_fu_420_p2(23 - 1 downto 0);
    trunc_ln_fu_202_p4 <= img_w(11 downto 4);
    zext_ln10_1_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln15_1_fu_304_p3),12));
    zext_ln10_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_296_p3),12));
    zext_ln12_1_fu_224_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_216_p3),11));
    zext_ln12_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln_fu_202_p4),11));
end behav;
