// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module DMA24bUnit_mm2s_DMA24b_mm2s (
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        STR_video_out_TDATA,
        STR_video_out_TKEEP,
        STR_video_out_TSTRB,
        STR_video_out_TUSER,
        STR_video_out_TLAST,
        image_w,
        image_h,
        BAR_image_in,
        ap_clk,
        ap_rst,
        BAR_image_in_ap_vld,
        image_w_ap_vld,
        image_h_ap_vld,
        ap_start,
        STR_video_out_TVALID,
        STR_video_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [127:0] m_axi_gmem_WDATA;
output  [15:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [127:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
output  [23:0] STR_video_out_TDATA;
output  [2:0] STR_video_out_TKEEP;
output  [2:0] STR_video_out_TSTRB;
output  [0:0] STR_video_out_TUSER;
output  [0:0] STR_video_out_TLAST;
input  [11:0] image_w;
input  [11:0] image_h;
input  [63:0] BAR_image_in;
input   ap_clk;
input   ap_rst;
input   BAR_image_in_ap_vld;
input   image_w_ap_vld;
input   image_h_ap_vld;
input   ap_start;
output   STR_video_out_TVALID;
input   STR_video_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    DMA24b_mm2s_fetch_U0_ap_start;
wire    DMA24b_mm2s_fetch_U0_ap_done;
wire    DMA24b_mm2s_fetch_U0_ap_continue;
wire    DMA24b_mm2s_fetch_U0_ap_idle;
wire    DMA24b_mm2s_fetch_U0_ap_ready;
wire    DMA24b_mm2s_fetch_U0_start_out;
wire    DMA24b_mm2s_fetch_U0_start_write;
wire    DMA24b_mm2s_fetch_U0_m_axi_gmem_AWVALID;
wire   [63:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_AWADDR;
wire   [0:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_AWID;
wire   [31:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_AWLEN;
wire   [2:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_AWSIZE;
wire   [1:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_AWBURST;
wire   [1:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_AWLOCK;
wire   [3:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_AWCACHE;
wire   [2:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_AWPROT;
wire   [3:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_AWQOS;
wire   [3:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_AWREGION;
wire   [0:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_AWUSER;
wire    DMA24b_mm2s_fetch_U0_m_axi_gmem_WVALID;
wire   [127:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_WDATA;
wire   [15:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_WSTRB;
wire    DMA24b_mm2s_fetch_U0_m_axi_gmem_WLAST;
wire   [0:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_WID;
wire   [0:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_WUSER;
wire    DMA24b_mm2s_fetch_U0_m_axi_gmem_ARVALID;
wire   [63:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_ARADDR;
wire   [0:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_ARID;
wire   [31:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_ARLEN;
wire   [2:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_ARSIZE;
wire   [1:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_ARBURST;
wire   [1:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_ARLOCK;
wire   [3:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_ARCACHE;
wire   [2:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_ARPROT;
wire   [3:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_ARQOS;
wire   [3:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_ARREGION;
wire   [0:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_ARUSER;
wire    DMA24b_mm2s_fetch_U0_m_axi_gmem_RREADY;
wire    DMA24b_mm2s_fetch_U0_m_axi_gmem_BREADY;
wire   [127:0] DMA24b_mm2s_fetch_U0_mm_fifo1_din;
wire    DMA24b_mm2s_fetch_U0_mm_fifo1_write;
wire   [11:0] DMA24b_mm2s_fetch_U0_img_w_out_din;
wire    DMA24b_mm2s_fetch_U0_img_w_out_write;
wire   [11:0] DMA24b_mm2s_fetch_U0_img_h_out_din;
wire    DMA24b_mm2s_fetch_U0_img_h_out_write;
wire    DMA24b_mm2s_streamout_U0_ap_start;
wire    DMA24b_mm2s_streamout_U0_ap_done;
wire    DMA24b_mm2s_streamout_U0_ap_continue;
wire    DMA24b_mm2s_streamout_U0_ap_idle;
wire    DMA24b_mm2s_streamout_U0_ap_ready;
wire    DMA24b_mm2s_streamout_U0_mm_fifo1_read;
wire   [23:0] DMA24b_mm2s_streamout_U0_STR_video_out_TDATA;
wire    DMA24b_mm2s_streamout_U0_STR_video_out_TVALID;
wire   [2:0] DMA24b_mm2s_streamout_U0_STR_video_out_TKEEP;
wire   [2:0] DMA24b_mm2s_streamout_U0_STR_video_out_TSTRB;
wire   [0:0] DMA24b_mm2s_streamout_U0_STR_video_out_TUSER;
wire   [0:0] DMA24b_mm2s_streamout_U0_STR_video_out_TLAST;
wire    DMA24b_mm2s_streamout_U0_img_w_read;
wire    DMA24b_mm2s_streamout_U0_img_h_read;
wire    ap_sync_continue;
wire    mm_fifo_full_n;
wire   [127:0] mm_fifo_dout;
wire    mm_fifo_empty_n;
wire    image_w_c_full_n;
wire   [11:0] image_w_c_dout;
wire    image_w_c_empty_n;
wire    image_h_c_full_n;
wire   [11:0] image_h_c_dout;
wire    image_h_c_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_DMA24b_mm2s_streamout_U0_din;
wire    start_for_DMA24b_mm2s_streamout_U0_full_n;
wire   [0:0] start_for_DMA24b_mm2s_streamout_U0_dout;
wire    start_for_DMA24b_mm2s_streamout_U0_empty_n;
wire    DMA24b_mm2s_streamout_U0_start_full_n;
wire    DMA24b_mm2s_streamout_U0_start_write;

DMA24bUnit_mm2s_DMA24b_mm2s_fetch DMA24b_mm2s_fetch_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(DMA24b_mm2s_fetch_U0_ap_start),
    .start_full_n(start_for_DMA24b_mm2s_streamout_U0_full_n),
    .ap_done(DMA24b_mm2s_fetch_U0_ap_done),
    .ap_continue(DMA24b_mm2s_fetch_U0_ap_continue),
    .ap_idle(DMA24b_mm2s_fetch_U0_ap_idle),
    .ap_ready(DMA24b_mm2s_fetch_U0_ap_ready),
    .start_out(DMA24b_mm2s_fetch_U0_start_out),
    .start_write(DMA24b_mm2s_fetch_U0_start_write),
    .m_axi_gmem_AWVALID(DMA24b_mm2s_fetch_U0_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(DMA24b_mm2s_fetch_U0_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(DMA24b_mm2s_fetch_U0_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(DMA24b_mm2s_fetch_U0_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(DMA24b_mm2s_fetch_U0_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(DMA24b_mm2s_fetch_U0_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(DMA24b_mm2s_fetch_U0_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(DMA24b_mm2s_fetch_U0_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(DMA24b_mm2s_fetch_U0_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(DMA24b_mm2s_fetch_U0_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(DMA24b_mm2s_fetch_U0_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(DMA24b_mm2s_fetch_U0_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(DMA24b_mm2s_fetch_U0_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(DMA24b_mm2s_fetch_U0_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(DMA24b_mm2s_fetch_U0_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(DMA24b_mm2s_fetch_U0_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(DMA24b_mm2s_fetch_U0_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(DMA24b_mm2s_fetch_U0_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(DMA24b_mm2s_fetch_U0_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_ARREADY),
    .m_axi_gmem_ARADDR(DMA24b_mm2s_fetch_U0_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(DMA24b_mm2s_fetch_U0_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(DMA24b_mm2s_fetch_U0_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(DMA24b_mm2s_fetch_U0_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(DMA24b_mm2s_fetch_U0_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(DMA24b_mm2s_fetch_U0_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(DMA24b_mm2s_fetch_U0_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(DMA24b_mm2s_fetch_U0_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(DMA24b_mm2s_fetch_U0_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(DMA24b_mm2s_fetch_U0_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(DMA24b_mm2s_fetch_U0_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_RVALID),
    .m_axi_gmem_RREADY(DMA24b_mm2s_fetch_U0_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_RID),
    .m_axi_gmem_RUSER(m_axi_gmem_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(DMA24b_mm2s_fetch_U0_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .mm_fifo1_din(DMA24b_mm2s_fetch_U0_mm_fifo1_din),
    .mm_fifo1_full_n(mm_fifo_full_n),
    .mm_fifo1_write(DMA24b_mm2s_fetch_U0_mm_fifo1_write),
    .mm_buffer(BAR_image_in),
    .img_w(image_w),
    .img_h(image_h),
    .img_w_out_din(DMA24b_mm2s_fetch_U0_img_w_out_din),
    .img_w_out_full_n(image_w_c_full_n),
    .img_w_out_write(DMA24b_mm2s_fetch_U0_img_w_out_write),
    .img_h_out_din(DMA24b_mm2s_fetch_U0_img_h_out_din),
    .img_h_out_full_n(image_h_c_full_n),
    .img_h_out_write(DMA24b_mm2s_fetch_U0_img_h_out_write)
);

DMA24bUnit_mm2s_DMA24b_mm2s_streamout DMA24b_mm2s_streamout_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(DMA24b_mm2s_streamout_U0_ap_start),
    .ap_done(DMA24b_mm2s_streamout_U0_ap_done),
    .ap_continue(DMA24b_mm2s_streamout_U0_ap_continue),
    .ap_idle(DMA24b_mm2s_streamout_U0_ap_idle),
    .ap_ready(DMA24b_mm2s_streamout_U0_ap_ready),
    .mm_fifo1_dout(mm_fifo_dout),
    .mm_fifo1_empty_n(mm_fifo_empty_n),
    .mm_fifo1_read(DMA24b_mm2s_streamout_U0_mm_fifo1_read),
    .STR_video_out_TDATA(DMA24b_mm2s_streamout_U0_STR_video_out_TDATA),
    .STR_video_out_TVALID(DMA24b_mm2s_streamout_U0_STR_video_out_TVALID),
    .STR_video_out_TREADY(STR_video_out_TREADY),
    .STR_video_out_TKEEP(DMA24b_mm2s_streamout_U0_STR_video_out_TKEEP),
    .STR_video_out_TSTRB(DMA24b_mm2s_streamout_U0_STR_video_out_TSTRB),
    .STR_video_out_TUSER(DMA24b_mm2s_streamout_U0_STR_video_out_TUSER),
    .STR_video_out_TLAST(DMA24b_mm2s_streamout_U0_STR_video_out_TLAST),
    .img_w_dout(image_w_c_dout),
    .img_w_empty_n(image_w_c_empty_n),
    .img_w_read(DMA24b_mm2s_streamout_U0_img_w_read),
    .img_h_dout(image_h_c_dout),
    .img_h_empty_n(image_h_c_empty_n),
    .img_h_read(DMA24b_mm2s_streamout_U0_img_h_read)
);

DMA24bUnit_mm2s_fifo_w128_d256_A mm_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DMA24b_mm2s_fetch_U0_mm_fifo1_din),
    .if_full_n(mm_fifo_full_n),
    .if_write(DMA24b_mm2s_fetch_U0_mm_fifo1_write),
    .if_dout(mm_fifo_dout),
    .if_empty_n(mm_fifo_empty_n),
    .if_read(DMA24b_mm2s_streamout_U0_mm_fifo1_read)
);

DMA24bUnit_mm2s_fifo_w12_d2_S image_w_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DMA24b_mm2s_fetch_U0_img_w_out_din),
    .if_full_n(image_w_c_full_n),
    .if_write(DMA24b_mm2s_fetch_U0_img_w_out_write),
    .if_dout(image_w_c_dout),
    .if_empty_n(image_w_c_empty_n),
    .if_read(DMA24b_mm2s_streamout_U0_img_w_read)
);

DMA24bUnit_mm2s_fifo_w12_d2_S image_h_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DMA24b_mm2s_fetch_U0_img_h_out_din),
    .if_full_n(image_h_c_full_n),
    .if_write(DMA24b_mm2s_fetch_U0_img_h_out_write),
    .if_dout(image_h_c_dout),
    .if_empty_n(image_h_c_empty_n),
    .if_read(DMA24b_mm2s_streamout_U0_img_h_read)
);

DMA24bUnit_mm2s_start_for_DMA24b_mm2s_streamout_U0 start_for_DMA24b_mm2s_streamout_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_DMA24b_mm2s_streamout_U0_din),
    .if_full_n(start_for_DMA24b_mm2s_streamout_U0_full_n),
    .if_write(DMA24b_mm2s_fetch_U0_start_write),
    .if_dout(start_for_DMA24b_mm2s_streamout_U0_dout),
    .if_empty_n(start_for_DMA24b_mm2s_streamout_U0_empty_n),
    .if_read(DMA24b_mm2s_streamout_U0_ap_ready)
);

assign DMA24b_mm2s_fetch_U0_ap_continue = 1'b1;

assign DMA24b_mm2s_fetch_U0_ap_start = ap_start;

assign DMA24b_mm2s_streamout_U0_ap_continue = ap_continue;

assign DMA24b_mm2s_streamout_U0_ap_start = start_for_DMA24b_mm2s_streamout_U0_empty_n;

assign DMA24b_mm2s_streamout_U0_start_full_n = 1'b1;

assign DMA24b_mm2s_streamout_U0_start_write = 1'b0;

assign STR_video_out_TDATA = DMA24b_mm2s_streamout_U0_STR_video_out_TDATA;

assign STR_video_out_TKEEP = DMA24b_mm2s_streamout_U0_STR_video_out_TKEEP;

assign STR_video_out_TLAST = DMA24b_mm2s_streamout_U0_STR_video_out_TLAST;

assign STR_video_out_TSTRB = DMA24b_mm2s_streamout_U0_STR_video_out_TSTRB;

assign STR_video_out_TUSER = DMA24b_mm2s_streamout_U0_STR_video_out_TUSER;

assign STR_video_out_TVALID = DMA24b_mm2s_streamout_U0_STR_video_out_TVALID;

assign ap_done = DMA24b_mm2s_streamout_U0_ap_done;

assign ap_idle = (DMA24b_mm2s_streamout_U0_ap_idle & DMA24b_mm2s_fetch_U0_ap_idle);

assign ap_ready = DMA24b_mm2s_fetch_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = DMA24b_mm2s_streamout_U0_ap_done;

assign ap_sync_ready = DMA24b_mm2s_fetch_U0_ap_ready;

assign m_axi_gmem_ARADDR = DMA24b_mm2s_fetch_U0_m_axi_gmem_ARADDR;

assign m_axi_gmem_ARBURST = DMA24b_mm2s_fetch_U0_m_axi_gmem_ARBURST;

assign m_axi_gmem_ARCACHE = DMA24b_mm2s_fetch_U0_m_axi_gmem_ARCACHE;

assign m_axi_gmem_ARID = DMA24b_mm2s_fetch_U0_m_axi_gmem_ARID;

assign m_axi_gmem_ARLEN = DMA24b_mm2s_fetch_U0_m_axi_gmem_ARLEN;

assign m_axi_gmem_ARLOCK = DMA24b_mm2s_fetch_U0_m_axi_gmem_ARLOCK;

assign m_axi_gmem_ARPROT = DMA24b_mm2s_fetch_U0_m_axi_gmem_ARPROT;

assign m_axi_gmem_ARQOS = DMA24b_mm2s_fetch_U0_m_axi_gmem_ARQOS;

assign m_axi_gmem_ARREGION = DMA24b_mm2s_fetch_U0_m_axi_gmem_ARREGION;

assign m_axi_gmem_ARSIZE = DMA24b_mm2s_fetch_U0_m_axi_gmem_ARSIZE;

assign m_axi_gmem_ARUSER = DMA24b_mm2s_fetch_U0_m_axi_gmem_ARUSER;

assign m_axi_gmem_ARVALID = DMA24b_mm2s_fetch_U0_m_axi_gmem_ARVALID;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_RREADY = DMA24b_mm2s_fetch_U0_m_axi_gmem_RREADY;

assign m_axi_gmem_WDATA = 128'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 16'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign start_for_DMA24b_mm2s_streamout_U0_din = 1'b1;

endmodule //DMA24bUnit_mm2s_DMA24b_mm2s
