// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module DMA24bUnit_mm2s_DMA24b_mm2s_fetch (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        mm_fifo1_din,
        mm_fifo1_full_n,
        mm_fifo1_write,
        mm_buffer,
        img_w,
        img_h,
        img_w_out_din,
        img_w_out_full_n,
        img_w_out_write,
        img_h_out_din,
        img_h_out_full_n,
        img_h_out_write
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_pp0_stage0 = 17'd32768;
parameter    ap_ST_fsm_state19 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [127:0] m_axi_gmem_WDATA;
output  [15:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [127:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
output  [127:0] mm_fifo1_din;
input   mm_fifo1_full_n;
output   mm_fifo1_write;
input  [63:0] mm_buffer;
input  [11:0] img_w;
input  [11:0] img_h;
output  [11:0] img_w_out_din;
input   img_w_out_full_n;
output   img_w_out_write;
output  [11:0] img_h_out_din;
input   img_h_out_full_n;
output   img_h_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg m_axi_gmem_ARVALID;
reg m_axi_gmem_RREADY;
reg mm_fifo1_write;
reg img_w_out_write;
reg img_h_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state9;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln15_reg_508;
reg    mm_fifo1_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln15_reg_508_pp0_iter1_reg;
reg    img_w_out_blk_n;
reg    img_h_out_blk_n;
reg   [11:0] indvar_flatten_reg_191;
reg   [0:0] tmp_reg_438;
wire   [0:0] cmp22_i_fu_246_p2;
reg   [0:0] cmp22_i_reg_444;
wire   [22:0] trunc_ln13_fu_252_p1;
reg   [22:0] trunc_ln13_reg_448;
wire    ap_CS_fsm_state4;
reg   [5:0] tmp_2_cast_reg_453;
wire   [5:0] sub_ln13_1_fu_285_p2;
reg   [5:0] sub_ln13_1_reg_459;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire  signed [31:0] sext_ln14_fu_322_p1;
reg  signed [31:0] sext_ln14_reg_469;
wire   [11:0] add_ln10_fu_334_p2;
reg   [11:0] add_ln10_reg_474;
wire   [11:0] add_ln14_fu_340_p2;
reg   [11:0] add_ln14_reg_479;
wire    ap_CS_fsm_state7;
wire   [23:0] empty_fu_375_p2;
reg   [23:0] empty_reg_487;
wire   [0:0] icmp_ln14_fu_346_p2;
reg   [59:0] trunc_ln1_reg_492;
wire    ap_CS_fsm_state8;
wire   [11:0] add_ln15_1_fu_409_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state16_pp0_stage0_iter0;
reg    ap_block_state17_pp0_stage0_iter1;
reg    ap_block_state18_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln15_fu_415_p2;
reg   [127:0] data_mm_buffer_V_reg_512;
wire    ap_CS_fsm_state15;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state16;
reg   [11:0] j_reg_180;
wire    ap_CS_fsm_state19;
wire  signed [63:0] sext_ln15_1_fu_399_p1;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] trunc_ln_fu_202_p4;
wire   [9:0] shl_ln_fu_216_p3;
wire   [10:0] zext_ln12_1_fu_224_p1;
wire   [10:0] zext_ln12_fu_212_p1;
wire  signed [10:0] beats_per_line_fu_228_p2;
wire  signed [23:0] grp_fu_420_p2;
wire   [22:0] sub_ln13_fu_264_p2;
wire   [5:0] tmp_1_cast_fu_269_p4;
wire   [5:0] select_ln13_fu_279_p3;
wire   [5:0] select_ln13_1_fu_291_p3;
wire  signed [8:0] shl_ln15_1_fu_304_p3;
wire   [10:0] shl_ln1_fu_296_p3;
wire  signed [10:0] sext_ln15_fu_312_p1;
wire   [10:0] add_ln15_fu_316_p2;
wire   [11:0] zext_ln10_fu_326_p1;
wire   [11:0] zext_ln10_1_fu_330_p1;
wire   [22:0] p_shl3_i_fu_351_p3;
wire   [18:0] p_shl4_i_fu_363_p3;
wire   [23:0] p_shl3_cast11_i_fu_359_p1;
wire   [23:0] p_shl4_cast12_i_fu_371_p1;
wire  signed [63:0] p_cast_i_fu_381_p1;
wire   [63:0] empty_62_fu_384_p2;
wire   [12:0] grp_fu_420_p1;
reg    grp_fu_420_ce;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [16:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 17'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

DMA24bUnit_mm2s_mul_mul_11s_13ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 24 ))
mul_mul_11s_13ns_24_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(beats_per_line_fu_228_p2),
    .din1(grp_fu_420_p1),
    .ce(grp_fu_420_ce),
    .dout(grp_fu_420_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln14_fu_346_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state16) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state15)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state16)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state16);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state15)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_fu_415_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_191 <= add_ln15_1_fu_409_p2;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        indvar_flatten_reg_191 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        j_reg_180 <= 12'd0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        j_reg_180 <= add_ln14_reg_479;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln10_reg_474[11 : 3] <= add_ln10_fu_334_p2[11 : 3];
        sext_ln14_reg_469[31 : 3] <= sext_ln14_fu_322_p1[31 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln14_reg_479 <= add_ln14_fu_340_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cmp22_i_reg_444 <= cmp22_i_fu_246_p2;
        tmp_reg_438 <= beats_per_line_fu_228_p2[32'd10];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln15_reg_508 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_mm_buffer_V_reg_512 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        empty_reg_487[23 : 7] <= empty_fu_375_p2[23 : 7];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln15_reg_508 <= icmp_ln15_fu_415_p2;
        icmp_ln15_reg_508_pp0_iter1_reg <= icmp_ln15_reg_508;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (tmp_reg_438 == 1'd1))) begin
        sub_ln13_1_reg_459 <= sub_ln13_1_fu_285_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_2_cast_reg_453 <= {{grp_fu_420_p2[22:17]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (tmp_reg_438 == 1'd1))) begin
        trunc_ln13_reg_448 <= trunc_ln13_fu_252_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (cmp22_i_reg_444 == 1'd1))) begin
        trunc_ln1_reg_492 <= {{empty_62_fu_384_p2[63:4]}};
    end
end

always @ (*) begin
    if ((icmp_ln15_fu_415_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state16 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state16 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln14_fu_346_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln15_reg_508 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (img_h_out_full_n == 1'b0) | (img_w_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_420_ce = 1'b1;
    end else begin
        grp_fu_420_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_h_out_blk_n = img_h_out_full_n;
    end else begin
        img_h_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (img_h_out_full_n == 1'b0) | (img_w_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_h_out_write = 1'b1;
    end else begin
        img_h_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_w_out_blk_n = img_w_out_full_n;
    end else begin
        img_w_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (img_h_out_full_n == 1'b0) | (img_w_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_w_out_write = 1'b1;
    end else begin
        img_w_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln14_fu_346_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln15_reg_508 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_508_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        mm_fifo1_blk_n = mm_fifo1_full_n;
    end else begin
        mm_fifo1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_508_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mm_fifo1_write = 1'b1;
    end else begin
        mm_fifo1_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (img_h_out_full_n == 1'b0) | (img_w_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln14_fu_346_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (cmp22_i_reg_444 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((m_axi_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln15_fu_415_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((icmp_ln15_fu_415_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_fu_334_p2 = (zext_ln10_fu_326_p1 + zext_ln10_1_fu_330_p1);

assign add_ln14_fu_340_p2 = (j_reg_180 + 12'd1);

assign add_ln15_1_fu_409_p2 = (indvar_flatten_reg_191 + 12'd1);

assign add_ln15_fu_316_p2 = ($signed(shl_ln1_fu_296_p3) + $signed(sext_ln15_fu_312_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((m_axi_gmem_RVALID == 1'b0) & (icmp_ln15_reg_508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln15_reg_508_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (mm_fifo1_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_gmem_RVALID == 1'b0) & (icmp_ln15_reg_508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln15_reg_508_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (mm_fifo1_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_gmem_RVALID == 1'b0) & (icmp_ln15_reg_508 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln15_reg_508_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (mm_fifo1_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0) | (img_h_out_full_n == 1'b0) | (img_w_out_full_n == 1'b0));
end

assign ap_block_state16_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state17_pp0_stage0_iter1 = ((m_axi_gmem_RVALID == 1'b0) & (icmp_ln15_reg_508 == 1'd0));
end

always @ (*) begin
    ap_block_state18_pp0_stage0_iter2 = ((icmp_ln15_reg_508_pp0_iter1_reg == 1'd0) & (mm_fifo1_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign beats_per_line_fu_228_p2 = (zext_ln12_1_fu_224_p1 - zext_ln12_fu_212_p1);

assign cmp22_i_fu_246_p2 = (($signed(beats_per_line_fu_228_p2) > $signed(11'd39)) ? 1'b1 : 1'b0);

assign empty_62_fu_384_p2 = ($signed(p_cast_i_fu_381_p1) + $signed(mm_buffer));

assign empty_fu_375_p2 = (p_shl3_cast11_i_fu_359_p1 - p_shl4_cast12_i_fu_371_p1);

assign grp_fu_420_p1 = 24'd3277;

assign icmp_ln14_fu_346_p2 = ((j_reg_180 == img_h) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_415_p2 = ((indvar_flatten_reg_191 == add_ln10_reg_474) ? 1'b1 : 1'b0);

assign img_h_out_din = img_h;

assign img_w_out_din = img_w;

assign m_axi_gmem_ARADDR = sext_ln15_1_fu_399_p1;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = sext_ln14_reg_469;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 128'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 16'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign mm_fifo1_din = data_mm_buffer_V_reg_512;

assign p_cast_i_fu_381_p1 = $signed(empty_reg_487);

assign p_shl3_cast11_i_fu_359_p1 = p_shl3_i_fu_351_p3;

assign p_shl3_i_fu_351_p3 = {{j_reg_180}, {11'd0}};

assign p_shl4_cast12_i_fu_371_p1 = p_shl4_i_fu_363_p3;

assign p_shl4_i_fu_363_p3 = {{j_reg_180}, {7'd0}};

assign select_ln13_1_fu_291_p3 = ((tmp_reg_438[0:0] == 1'b1) ? sub_ln13_1_reg_459 : tmp_2_cast_reg_453);

assign select_ln13_fu_279_p3 = ((tmp_reg_438[0:0] == 1'b1) ? tmp_1_cast_fu_269_p4 : tmp_2_cast_reg_453);

assign sext_ln14_fu_322_p1 = $signed(add_ln15_fu_316_p2);

assign sext_ln15_1_fu_399_p1 = $signed(trunc_ln1_reg_492);

assign sext_ln15_fu_312_p1 = shl_ln15_1_fu_304_p3;

assign shl_ln15_1_fu_304_p3 = {{select_ln13_1_fu_291_p3}, {3'd0}};

assign shl_ln1_fu_296_p3 = {{select_ln13_1_fu_291_p3}, {5'd0}};

assign shl_ln_fu_216_p3 = {{trunc_ln_fu_202_p4}, {2'd0}};

assign start_out = real_start;

assign sub_ln13_1_fu_285_p2 = (6'd0 - select_ln13_fu_279_p3);

assign sub_ln13_fu_264_p2 = (23'd0 - trunc_ln13_reg_448);

assign tmp_1_cast_fu_269_p4 = {{sub_ln13_fu_264_p2[22:17]}};

assign trunc_ln13_fu_252_p1 = grp_fu_420_p2[22:0];

assign trunc_ln_fu_202_p4 = {{img_w[11:4]}};

assign zext_ln10_1_fu_330_p1 = $unsigned(shl_ln15_1_fu_304_p3);

assign zext_ln10_fu_326_p1 = shl_ln1_fu_296_p3;

assign zext_ln12_1_fu_224_p1 = shl_ln_fu_216_p3;

assign zext_ln12_fu_212_p1 = trunc_ln_fu_202_p4;

always @ (posedge ap_clk) begin
    sext_ln14_reg_469[2:0] <= 3'b000;
    add_ln10_reg_474[2:0] <= 3'b000;
    empty_reg_487[6:0] <= 7'b0000000;
end

endmodule //DMA24bUnit_mm2s_DMA24b_mm2s_fetch
