// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="DMA24bUnit_mm2s_DMA24bUnit_mm2s,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=6.660000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.861800,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=20,HLS_SYN_DSP=0,HLS_SYN_FF=1588,HLS_SYN_LUT=2040,HLS_VERSION=2020_2}" *)

module DMA24bUnit_mm2s (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        STR_video_out_TDATA,
        STR_video_out_TVALID,
        STR_video_out_TREADY,
        STR_video_out_TKEEP,
        STR_video_out_TSTRB,
        STR_video_out_TUSER,
        STR_video_out_TLAST,
        image_w,
        image_h,
        image_in
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_M_AXI_GMEM_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
output  [23:0] STR_video_out_TDATA;
output   STR_video_out_TVALID;
input   STR_video_out_TREADY;
output  [2:0] STR_video_out_TKEEP;
output  [2:0] STR_video_out_TSTRB;
output  [0:0] STR_video_out_TUSER;
output  [0:0] STR_video_out_TLAST;
input  [11:0] image_w;
input  [11:0] image_h;
input  [63:0] image_in;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    gmem_AWREADY;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [127:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
wire    grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWVALID;
wire   [63:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWADDR;
wire   [0:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWID;
wire   [31:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWLEN;
wire   [2:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWSIZE;
wire   [1:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWBURST;
wire   [1:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWLOCK;
wire   [3:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWCACHE;
wire   [2:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWPROT;
wire   [3:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWQOS;
wire   [3:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWREGION;
wire   [0:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWUSER;
wire    grp_DMA24b_mm2s_fu_78_m_axi_gmem_WVALID;
wire   [127:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_WDATA;
wire   [15:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_WSTRB;
wire    grp_DMA24b_mm2s_fu_78_m_axi_gmem_WLAST;
wire   [0:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_WID;
wire   [0:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_WUSER;
wire    grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARVALID;
wire   [63:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARADDR;
wire   [0:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARID;
wire   [31:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARLEN;
wire   [2:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARSIZE;
wire   [1:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARBURST;
wire   [1:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARLOCK;
wire   [3:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARCACHE;
wire   [2:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARPROT;
wire   [3:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARQOS;
wire   [3:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARREGION;
wire   [0:0] grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARUSER;
wire    grp_DMA24b_mm2s_fu_78_m_axi_gmem_RREADY;
wire    grp_DMA24b_mm2s_fu_78_m_axi_gmem_BREADY;
wire   [23:0] grp_DMA24b_mm2s_fu_78_STR_video_out_TDATA;
wire   [2:0] grp_DMA24b_mm2s_fu_78_STR_video_out_TKEEP;
wire   [2:0] grp_DMA24b_mm2s_fu_78_STR_video_out_TSTRB;
wire   [0:0] grp_DMA24b_mm2s_fu_78_STR_video_out_TUSER;
wire   [0:0] grp_DMA24b_mm2s_fu_78_STR_video_out_TLAST;
wire    grp_DMA24b_mm2s_fu_78_ap_start;
wire    grp_DMA24b_mm2s_fu_78_STR_video_out_TVALID;
wire    grp_DMA24b_mm2s_fu_78_STR_video_out_TREADY;
wire    grp_DMA24b_mm2s_fu_78_ap_done;
wire    grp_DMA24b_mm2s_fu_78_ap_ready;
wire    grp_DMA24b_mm2s_fu_78_ap_idle;
reg    grp_DMA24b_mm2s_fu_78_ap_continue;
reg    grp_DMA24b_mm2s_fu_78_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_sync_grp_DMA24b_mm2s_fu_78_ap_ready;
wire    ap_sync_grp_DMA24b_mm2s_fu_78_ap_done;
reg    ap_block_state2_on_subcall_done;
reg    ap_sync_reg_grp_DMA24b_mm2s_fu_78_ap_ready;
reg    ap_sync_reg_grp_DMA24b_mm2s_fu_78_ap_done;
wire    ap_CS_fsm_state3;
wire    regslice_both_STR_video_out_V_data_V_U_apdone_blk;
reg   [2:0] ap_NS_fsm;
wire    STR_video_out_TREADY_int_regslice;
wire    regslice_both_STR_video_out_V_data_V_U_vld_out;
wire    regslice_both_STR_video_out_V_keep_V_U_apdone_blk;
wire    regslice_both_STR_video_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_STR_video_out_V_keep_V_U_vld_out;
wire    regslice_both_STR_video_out_V_strb_V_U_apdone_blk;
wire    regslice_both_STR_video_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_STR_video_out_V_strb_V_U_vld_out;
wire    regslice_both_STR_video_out_V_user_V_U_apdone_blk;
wire    regslice_both_STR_video_out_V_user_V_U_ack_in_dummy;
wire    regslice_both_STR_video_out_V_user_V_U_vld_out;
wire    regslice_both_STR_video_out_V_last_V_U_apdone_blk;
wire    regslice_both_STR_video_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_STR_video_out_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_DMA24b_mm2s_fu_78_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_DMA24b_mm2s_fu_78_ap_ready = 1'b0;
#0 ap_sync_reg_grp_DMA24b_mm2s_fu_78_ap_done = 1'b0;
end

DMA24bUnit_mm2s_gmem_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 128 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARADDR),
    .I_ARID(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARID),
    .I_ARLEN(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARLEN),
    .I_ARSIZE(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARSIZE),
    .I_ARLOCK(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARLOCK),
    .I_ARCACHE(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARCACHE),
    .I_ARQOS(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARQOS),
    .I_ARPROT(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARPROT),
    .I_ARUSER(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARUSER),
    .I_ARBURST(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARBURST),
    .I_ARREGION(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARREGION),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(128'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(16'd0),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

DMA24bUnit_mm2s_DMA24b_mm2s grp_DMA24b_mm2s_fu_78(
    .m_axi_gmem_AWVALID(grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_DMA24b_mm2s_fu_78_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_DMA24b_mm2s_fu_78_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_DMA24b_mm2s_fu_78_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_DMA24b_mm2s_fu_78_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_DMA24b_mm2s_fu_78_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_DMA24b_mm2s_fu_78_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_DMA24b_mm2s_fu_78_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_DMA24b_mm2s_fu_78_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(gmem_RLAST),
    .m_axi_gmem_RID(gmem_RID),
    .m_axi_gmem_RUSER(gmem_RUSER),
    .m_axi_gmem_RRESP(gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_DMA24b_mm2s_fu_78_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .STR_video_out_TDATA(grp_DMA24b_mm2s_fu_78_STR_video_out_TDATA),
    .STR_video_out_TKEEP(grp_DMA24b_mm2s_fu_78_STR_video_out_TKEEP),
    .STR_video_out_TSTRB(grp_DMA24b_mm2s_fu_78_STR_video_out_TSTRB),
    .STR_video_out_TUSER(grp_DMA24b_mm2s_fu_78_STR_video_out_TUSER),
    .STR_video_out_TLAST(grp_DMA24b_mm2s_fu_78_STR_video_out_TLAST),
    .image_w(image_w),
    .image_h(image_h),
    .BAR_image_in(image_in),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .BAR_image_in_ap_vld(1'b1),
    .image_w_ap_vld(1'b1),
    .image_h_ap_vld(1'b1),
    .ap_start(grp_DMA24b_mm2s_fu_78_ap_start),
    .STR_video_out_TVALID(grp_DMA24b_mm2s_fu_78_STR_video_out_TVALID),
    .STR_video_out_TREADY(grp_DMA24b_mm2s_fu_78_STR_video_out_TREADY),
    .ap_done(grp_DMA24b_mm2s_fu_78_ap_done),
    .ap_ready(grp_DMA24b_mm2s_fu_78_ap_ready),
    .ap_idle(grp_DMA24b_mm2s_fu_78_ap_idle),
    .ap_continue(grp_DMA24b_mm2s_fu_78_ap_continue)
);

DMA24bUnit_mm2s_regslice_both #(
    .DataWidth( 24 ))
regslice_both_STR_video_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_DMA24b_mm2s_fu_78_STR_video_out_TDATA),
    .vld_in(grp_DMA24b_mm2s_fu_78_STR_video_out_TVALID),
    .ack_in(STR_video_out_TREADY_int_regslice),
    .data_out(STR_video_out_TDATA),
    .vld_out(regslice_both_STR_video_out_V_data_V_U_vld_out),
    .ack_out(STR_video_out_TREADY),
    .apdone_blk(regslice_both_STR_video_out_V_data_V_U_apdone_blk)
);

DMA24bUnit_mm2s_regslice_both #(
    .DataWidth( 3 ))
regslice_both_STR_video_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_DMA24b_mm2s_fu_78_STR_video_out_TKEEP),
    .vld_in(grp_DMA24b_mm2s_fu_78_STR_video_out_TVALID),
    .ack_in(regslice_both_STR_video_out_V_keep_V_U_ack_in_dummy),
    .data_out(STR_video_out_TKEEP),
    .vld_out(regslice_both_STR_video_out_V_keep_V_U_vld_out),
    .ack_out(STR_video_out_TREADY),
    .apdone_blk(regslice_both_STR_video_out_V_keep_V_U_apdone_blk)
);

DMA24bUnit_mm2s_regslice_both #(
    .DataWidth( 3 ))
regslice_both_STR_video_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_DMA24b_mm2s_fu_78_STR_video_out_TSTRB),
    .vld_in(grp_DMA24b_mm2s_fu_78_STR_video_out_TVALID),
    .ack_in(regslice_both_STR_video_out_V_strb_V_U_ack_in_dummy),
    .data_out(STR_video_out_TSTRB),
    .vld_out(regslice_both_STR_video_out_V_strb_V_U_vld_out),
    .ack_out(STR_video_out_TREADY),
    .apdone_blk(regslice_both_STR_video_out_V_strb_V_U_apdone_blk)
);

DMA24bUnit_mm2s_regslice_both #(
    .DataWidth( 1 ))
regslice_both_STR_video_out_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_DMA24b_mm2s_fu_78_STR_video_out_TUSER),
    .vld_in(grp_DMA24b_mm2s_fu_78_STR_video_out_TVALID),
    .ack_in(regslice_both_STR_video_out_V_user_V_U_ack_in_dummy),
    .data_out(STR_video_out_TUSER),
    .vld_out(regslice_both_STR_video_out_V_user_V_U_vld_out),
    .ack_out(STR_video_out_TREADY),
    .apdone_blk(regslice_both_STR_video_out_V_user_V_U_apdone_blk)
);

DMA24bUnit_mm2s_regslice_both #(
    .DataWidth( 1 ))
regslice_both_STR_video_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_DMA24b_mm2s_fu_78_STR_video_out_TLAST),
    .vld_in(grp_DMA24b_mm2s_fu_78_STR_video_out_TVALID),
    .ack_in(regslice_both_STR_video_out_V_last_V_U_ack_in_dummy),
    .data_out(STR_video_out_TLAST),
    .vld_out(regslice_both_STR_video_out_V_last_V_U_vld_out),
    .ack_out(STR_video_out_TREADY),
    .apdone_blk(regslice_both_STR_video_out_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_DMA24b_mm2s_fu_78_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_sync_reg_grp_DMA24b_mm2s_fu_78_ap_done <= 1'b0;
        end else if ((grp_DMA24b_mm2s_fu_78_ap_done == 1'b1)) begin
            ap_sync_reg_grp_DMA24b_mm2s_fu_78_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_DMA24b_mm2s_fu_78_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_sync_reg_grp_DMA24b_mm2s_fu_78_ap_ready <= 1'b0;
        end else if ((grp_DMA24b_mm2s_fu_78_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_DMA24b_mm2s_fu_78_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_DMA24b_mm2s_fu_78_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_sync_grp_DMA24b_mm2s_fu_78_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
            grp_DMA24b_mm2s_fu_78_ap_start_reg <= 1'b1;
        end else if ((grp_DMA24b_mm2s_fu_78_ap_ready == 1'b1)) begin
            grp_DMA24b_mm2s_fu_78_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((regslice_both_STR_video_out_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_STR_video_out_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem_ARVALID = grp_DMA24b_mm2s_fu_78_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem_RREADY = grp_DMA24b_mm2s_fu_78_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_DMA24b_mm2s_fu_78_ap_continue = 1'b1;
    end else begin
        grp_DMA24b_mm2s_fu_78_ap_continue = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((regslice_both_STR_video_out_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign STR_video_out_TVALID = regslice_both_STR_video_out_V_data_V_U_vld_out;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((ap_sync_grp_DMA24b_mm2s_fu_78_ap_ready & ap_sync_grp_DMA24b_mm2s_fu_78_ap_done) == 1'b0);
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_grp_DMA24b_mm2s_fu_78_ap_done = (grp_DMA24b_mm2s_fu_78_ap_done | ap_sync_reg_grp_DMA24b_mm2s_fu_78_ap_done);

assign ap_sync_grp_DMA24b_mm2s_fu_78_ap_ready = (grp_DMA24b_mm2s_fu_78_ap_ready | ap_sync_reg_grp_DMA24b_mm2s_fu_78_ap_ready);

assign grp_DMA24b_mm2s_fu_78_STR_video_out_TREADY = (ap_CS_fsm_state2 & STR_video_out_TREADY_int_regslice);

assign grp_DMA24b_mm2s_fu_78_ap_start = grp_DMA24b_mm2s_fu_78_ap_start_reg;

endmodule //DMA24bUnit_mm2s
