#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Sep 03 13:57:47 CEST 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_environnement_behav -key {Behavioral:sim_1:Functional:tb_environnement} -tclbatch tb_environnement.tcl -protoinst "protoinst_files/design_1.protoinst" -view /mnt/isaac_sbay0/lbo-ws/Projects/DVR-008-002/Base_Design_Project/Reference_design_project_2020.2/src/sim/tb_socora_gpio_behav.wcfg -view /mnt/isaac_sbay0/lbo-ws/Projects/DVR-008-002/Base_Design_Project/Reference_design_project_2020.2/src/sim/tb_environnement_behav.wcfg -log simulate.log"
xsim tb_environnement_behav -key {Behavioral:sim_1:Functional:tb_environnement} -tclbatch tb_environnement.tcl -protoinst "protoinst_files/design_1.protoinst" -view /mnt/isaac_sbay0/lbo-ws/Projects/DVR-008-002/Base_Design_Project/Reference_design_project_2020.2/src/sim/tb_socora_gpio_behav.wcfg -view /mnt/isaac_sbay0/lbo-ws/Projects/DVR-008-002/Base_Design_Project/Reference_design_project_2020.2/src/sim/tb_environnement_behav.wcfg -log simulate.log

